#-----------------------------------------------------------------------------
# HRGZDevEngine DOOM - PlayStation Portable (PSP) Makefile
# Built using the official PSPDEV SDK (https://pspdev.github.io)
#-----------------------------------------------------------------------------

TARGET = HRGZDOOM

# Engine Core & Playsim Source Files
DOOM_OBJS = \
    src/doom/am_map.o \
    src/doom/d_items.o \
    src/doom/d_main.o \
    src/doom/d_net.o \
    src/doom/doomdef.o \
    src/doom/doomstat.o \
    src/doom/dstrings.o \
    src/doom/f_finale.o \
    src/doom/f_wipe.o \
    src/doom/g_game.o \
    src/doom/hu_lib.o \
    src/doom/hu_stuff.o \
    src/doom/info.o \
    src/doom/m_argv.o \
    src/doom/m_bbox.o \
    src/doom/m_cheat.o \
    src/doom/m_fixed.o \
    src/doom/m_menu.o \
    src/doom/m_misc.o \
    src/doom/m_random.o \
    src/doom/m_swap.o \
    src/doom/p_ceilng.o \
    src/doom/p_doors.o \
    src/doom/p_enemy.o \
    src/doom/p_floor.o \
    src/doom/p_inter.o \
    src/doom/p_lights.o \
    src/doom/p_map.o \
    src/doom/p_maputl.o \
    src/doom/p_mobj.o \
    src/doom/p_plats.o \
    src/doom/p_pspr.o \
    src/doom/p_saveg.o \
    src/doom/p_setup.o \
    src/doom/p_sight.o \
    src/doom/p_spec.o \
    src/doom/p_switch.o \
    src/doom/p_telept.o \
    src/doom/p_tick.o \
    src/doom/p_user.o \
    src/doom/r_bsp.o \
    src/doom/r_data.o \
    src/doom/r_draw.o \
    src/doom/r_main.o \
    src/doom/r_plane.o \
    src/doom/r_segs.o \
    src/doom/r_sky.o \
    src/doom/r_things.o \
    src/doom/s_sound.o \
    src/doom/sounds.o \
    src/doom/st_lib.o \
    src/doom/st_stuff.o \
    src/doom/tables.o \
    src/doom/v_video.o \
    src/doom/w_wad.o \
    src/doom/wi_stuff.o \
    src/doom/z_zone.o

# Common Hardware Abstraction Layer
COMMON_OBJS = \
    src/hal/common/i_gamepad.o \
    src/hal/common/i_sound_mixer.o \
    src/hal/common/i_mus2midi.o

# PSP Hardware Abstraction Layer
PSP_OBJS = \
    src/hal/psp/i_main_psp.o \
    src/hal/psp/i_video_psp.o \
    src/hal/psp/i_sound_psp.o \
    src/hal/psp/i_system_psp.o \
    src/hal/psp/i_net_psp.o

OBJS = $(DOOM_OBJS) $(COMMON_OBJS) $(PSP_OBJS)

INCDIR = src/doom src/hal/common src/hal/psp

CFLAGS = -O2 -G0 -Wall -Wno-unused -Wno-parentheses -std=c99 -DPSP -D__PSP__ -D_DEFAULT_SOURCE -D_GNU_SOURCE
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti
ASFLAGS = $(CFLAGS)

LIBDIR =
LDFLAGS =
LIBS = -lpspgu -lpspaudio -lpspctrl -lpspge -lpspdisplay -lpsprtc -lpsppower -lpspdebug -lm

# Build PRX and Package as EBOOT.PBP
BUILD_PRX = 1
PSP_FW_VERSION = 500
EXTRA_TARGETS = EBOOT.PBP
PSP_EBOOT_TITLE = HRGZDevEngine DOOM
PSP_EBOOT_ICON = src/hal/psp/ICON0.PNG

PSPSDK = $(shell psp-config --pspsdk-path)
include $(PSPSDK)/lib/build.mak

